### ISSUE TITLE
error?and how solve this problem below

### ISSUE THREAD

**Issue by yutinyang** [spytensor/pytorch-image-classification#1]
Get Better model,the accuracy has updated from : 0 to :27.6502742767334
Traceback (most recent call last):
  File "main.py", line 163, in <module>
    torch.save(model.state_dict(), config.weights_path)
  File "/home/xxx/anaconda3/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 161, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/xxx/anaconda3/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 116, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/Downloads/pytorch-image-classification-master/logs/resnet152_params.pkl'

**Comment by spytensor** [comment]
@yutinyang  make sure you have mkdir "./logs/",I will update this repo soon for better.
